$axure.loadCurrentPage({
  "url":"编辑页面_1.html",
  "generationDate":new Date(1401345418896.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1f14453ec6974695af2ef031861094e9",
    "type":"Axure:Page",
    "name":"编辑页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"113189c83472446b8e906dad46b20c39",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"d1816b87768546869fbf5f5fc4d1ba7d"},
{
          "id":"3b88108d1fa846ddb2b8244a66ef8ddf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009966},
            "location":{
              "x":10,
              "y":660},
            "size":{
              "width":12,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e4cf0a8ae0e43d683f8864804e8d57a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009966},
                "location":{
                  "x":10,
                  "y":660},
                "size":{
                  "width":12,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/常用信息/u34.png"}},
{
          "id":"7d85bbacbdae4abca31e8d1a8d808d9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":50},
            "size":{
              "width":1040,
              "height":710},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36ab025bd3b2432c836ee7ccf03018e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":50},
                "size":{
                  "width":1040,
                  "height":710},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增问题/u32.png"}},
{
          "id":"76f84f261c96488080a626e520e5f946",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":84},
            "size":{
              "width":1040,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/记录问题管理/u34_line.png"}},
{
          "id":"96b64a272252435aab5772a89e52387a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei-Bold', 'Microsoft YaHei Bold', 'Microsoft YaHei'",
            "fontSize":"16px",
            "location":{
              "x":226,
              "y":61},
            "size":{
              "width":65,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeba11f5bd744ed8adcdf9aee6a78335",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei-Bold', 'Microsoft YaHei Bold', 'Microsoft YaHei'",
                "fontSize":"16px",
                "location":{
                  "x":226,
                  "y":61},
                "size":{
                  "width":65,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ae968946ef24835a98a532e6fe8a8ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":249,
              "y":113},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c3391d7bbe943b0bf44f5f67f727682",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":249,
                  "y":113},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ae97deab92843b8b152dfdc05985438",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":249,
              "y":141},
            "size":{
              "width":101,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"5c6aece25b8d4a9f9c4d1c3340bcade0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":422,
              "y":112},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1df1038b19ff44fe83ccc1b6e41e0b94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":422,
                  "y":112},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53dfb69856f54847b65729a7e8537a24",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":422,
              "y":140},
            "size":{
              "width":108,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"cb4c67c2dc6e4fe08aa870c47acc6ee6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":610,
              "y":112},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"999bf05491704b71878da72485644654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":610,
                  "y":112},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"718540553a61418f8566db593ed33a37",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":610,
              "y":140},
            "size":{
              "width":160,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"7d286e9dc3b74f2b845ce0a59a476229",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":849,
              "y":112},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8928c81715324c2487509ec139ae7c56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":849,
                  "y":112},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94e5c3c3996f4dab9651ef0716b6a2eb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":849,
              "y":140},
            "size":{
              "width":131,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"5582f3e489af45bdb546cacefa78ce85",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":1060,
              "y":112},
            "size":{
              "width":97,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55107131750d42ca890faa994566424d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":1060,
                  "y":112},
                "size":{
                  "width":97,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08cd74d4ab6e49918276ac73e4c2cc58",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1060,
              "y":140},
            "size":{
              "width":160,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"f569d770eb0248cfa4fe66f8efb7b95f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":249,
              "y":220},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d75649696a084ebab97fdb5ca4ae93ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":249,
                  "y":220},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4bd30f169a14a219da3ee7b30036d8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":422,
              "y":220},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33705a1715b34752a6c0a9d8e4506675",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":422,
                  "y":220},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be8dccf1340d44a4a7df8bd7ed9d1409",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":249,
              "y":251},
            "size":{
              "width":120,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"3e36d471f6d3499b8fbb8ded67af13c7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":422,
              "y":251},
            "size":{
              "width":81,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"76eeea9294e84a64a7f1f259d860772a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":506,
              "y":251},
            "size":{
              "width":80,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"e73192537d5b4c16b54df87dc88c50be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":620,
              "y":220},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06559bd826594d56880ffc4b9bc71e2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":620,
                  "y":220},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac68cef514814bbdaa4bec159a3ce847",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":620,
              "y":251},
            "size":{
              "width":81,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"fd854e93ed424bdba49a72da838143a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":249,
              "y":312},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4099a0d18859411eb6a2e1ddfa8e5a35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":249,
                  "y":312},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83cb33dc5ca34d61a85024ee962a2610",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":249,
              "y":351},
            "size":{
              "width":851,
              "height":99}},
          "adaptiveStyles":{
}},
{
          "id":"53a4a6942a0c41c3a1df0e2f028ff775",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":249,
              "y":482},
            "size":{
              "width":118,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3587aa3f3f1141a78e9e1ab8f750d7b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":249,
                  "y":482},
                "size":{
                  "width":118,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fc49f4a64e0438b9bb71e287d1a4008",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":510},
            "size":{
              "width":851,
              "height":100}},
          "adaptiveStyles":{
}},
{
          "id":"a2e6ef6730ee4930b9afabd55f5ea995",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":249,
              "y":690},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6e2186327fe47bfb12b8a9ba34a5f52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":249,
                  "y":690},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 编辑成功",
                      "target":{
                        "targetType":"page",
                        "url":"编辑成功.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/查看公告/u47.png"}},
{
          "id":"35037caee6984c6888cce89eb209bf8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":491,
              "y":690},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6995cf700760463f94805d59406db313",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":491,
                  "y":690},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 记录问题管理",
                      "target":{
                        "targetType":"page",
                        "url":"记录问题管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/查看公告/u47.png"}},
{
          "id":"3145653e5843417a81a5c9d860106801",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":740,
              "y":220},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a081202137442b78423b821524774eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":740,
                  "y":220},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f3206de8f3a4d38878f7e566ac6fa80",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":740,
              "y":251},
            "size":{
              "width":160,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"a3512fbcbeea45fe823387dd48295e95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":256,
              "y":362},
            "size":{
              "width":824,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0249e0c7bf0a4073ab48376659a8e66c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":256,
                  "y":362},
                "size":{
                  "width":824,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d3ec490225a45868091aa54d64af497",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":258,
              "y":519},
            "size":{
              "width":733,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6a31298947a49949dcc322f47c8fedd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":519},
                "size":{
                  "width":733,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d1816b87768546869fbf5f5fc4d1ba7d":{
      "packageId":"d1816b87768546869fbf5f5fc4d1ba7d",
      "type":"Axure:Master",
      "name":"公共功能",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a95411bbce364a6e8352ec8cb4ef3e3a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":38,
                "y":20},
              "size":{
                "width":1280,
                "height":1210},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF777777}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2c263b778f3a4f8db528af20a297dcb2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":38,
                    "y":20},
                  "size":{
                    "width":1280,
                    "height":1210},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF777777}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u1.png"}},
{
            "id":"fda5b479da1c4a31aa6e7e1484e98d5a",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":207,
                "y":21},
              "size":{
                "width":10,
                "height":1209},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF777777}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/u3_line.png"}},
{
            "id":"e15a802047e24c6a8c6bbdd84bd40c4d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":93},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7186e364edd54114b5476b016aa6847d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":93},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 常用信息",
                        "target":{
                          "targetType":"page",
                          "url":"常用信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"f45315029c354fc2bb32d5df72b94467",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":159},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9427c2c800c545ddb79693d3c6922018",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":159},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 内部公告",
                        "target":{
                          "targetType":"page",
                          "url":"内部公告.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"1c9d8c816b3d403ebd4083fee7459de0",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":233},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"436c05d31fb240c7a15355b46989eb53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":233},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 公告管理",
                        "target":{
                          "targetType":"page",
                          "url":"公告管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"3755540f080e46beb2bd3815ca11ae37",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":397},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7ffa024de06848fc937f793c3f8211b0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":397},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 新调度中心",
                        "target":{
                          "targetType":"page",
                          "url":"新调度中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"d3eb8bdcb593413584c06e8384bee766",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":462},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a0d859f938e64a78871be545d525b983",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":462},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 短信平台",
                        "target":{
                          "targetType":"page",
                          "url":"短信平台.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"06ba4fbbbbfb4f1fb3caaaea015f6da1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":535},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"52dc334939f3434eb5a5560cdc121ba7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":535},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 作废订单",
                        "target":{
                          "targetType":"page",
                          "url":"作废订单.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"2e73a5717ec84c19b9077d7d2721132d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":608},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7a610aef328f4144b80d2dd241739021",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":608},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 通话记录",
                        "target":{
                          "targetType":"page",
                          "url":"通话记录.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"2218fe453a384502a76a6eb94c7ebbf1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":680},
              "size":{
                "width":121,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fb59f2b7a37d4392a956f2da24ef6502",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":680},
                  "size":{
                    "width":121,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 记录问题管理",
                        "target":{
                          "targetType":"page",
                          "url":"记录问题管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"c114e5842caf40d59a85dc40d53ff196",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":752},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1e1fc06d542745b4acd841910e45f4ad",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":752},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 修改密码",
                        "target":{
                          "targetType":"page",
                          "url":"修改密码.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"d0ad9c0b5ac3427d8a864e7a4955d76e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":74,
                "y":264},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7052978533a42b79d6f7beda7a8d046",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":74,
                    "y":264},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 新增公告",
                        "target":{
                          "targetType":"page",
                          "url":"新增公告.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"740cec6f294146f69cc993d8006577b3",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":74,
                "y":291},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f8f6f0e9b3f5432391c39effc5eb5b09",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":74,
                    "y":291},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 公司公告",
                        "target":{
                          "targetType":"page",
                          "url":"公司公告.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"762dc5fb47754c9a9db0bdf659286709",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":74,
                "y":318},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"680b7a13f6b944feb7e82998563637f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":74,
                    "y":318},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 内部公告",
                        "target":{
                          "targetType":"page",
                          "url":"内部公告_1.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"4d7292103726456a963a15507a1e2755",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":74,
                "y":345},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8b05e2b571f441e6881f0dfdb45e1763",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":74,
                    "y":345},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 培训教程",
                        "target":{
                          "targetType":"page",
                          "url":"培训教程.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "113189c83472446b8e906dad46b20c39":{
      "scriptId":"u0",
      "a95411bbce364a6e8352ec8cb4ef3e3a":{
        "scriptId":"u1"},
      "2c263b778f3a4f8db528af20a297dcb2":{
        "scriptId":"u2"},
      "fda5b479da1c4a31aa6e7e1484e98d5a":{
        "scriptId":"u3"},
      "e15a802047e24c6a8c6bbdd84bd40c4d":{
        "scriptId":"u4"},
      "7186e364edd54114b5476b016aa6847d":{
        "scriptId":"u5"},
      "f45315029c354fc2bb32d5df72b94467":{
        "scriptId":"u6"},
      "9427c2c800c545ddb79693d3c6922018":{
        "scriptId":"u7"},
      "1c9d8c816b3d403ebd4083fee7459de0":{
        "scriptId":"u8"},
      "436c05d31fb240c7a15355b46989eb53":{
        "scriptId":"u9"},
      "3755540f080e46beb2bd3815ca11ae37":{
        "scriptId":"u10"},
      "7ffa024de06848fc937f793c3f8211b0":{
        "scriptId":"u11"},
      "d3eb8bdcb593413584c06e8384bee766":{
        "scriptId":"u12"},
      "a0d859f938e64a78871be545d525b983":{
        "scriptId":"u13"},
      "06ba4fbbbbfb4f1fb3caaaea015f6da1":{
        "scriptId":"u14"},
      "52dc334939f3434eb5a5560cdc121ba7":{
        "scriptId":"u15"},
      "2e73a5717ec84c19b9077d7d2721132d":{
        "scriptId":"u16"},
      "7a610aef328f4144b80d2dd241739021":{
        "scriptId":"u17"},
      "2218fe453a384502a76a6eb94c7ebbf1":{
        "scriptId":"u18"},
      "fb59f2b7a37d4392a956f2da24ef6502":{
        "scriptId":"u19"},
      "c114e5842caf40d59a85dc40d53ff196":{
        "scriptId":"u20"},
      "1e1fc06d542745b4acd841910e45f4ad":{
        "scriptId":"u21"},
      "d0ad9c0b5ac3427d8a864e7a4955d76e":{
        "scriptId":"u22"},
      "c7052978533a42b79d6f7beda7a8d046":{
        "scriptId":"u23"},
      "740cec6f294146f69cc993d8006577b3":{
        "scriptId":"u24"},
      "f8f6f0e9b3f5432391c39effc5eb5b09":{
        "scriptId":"u25"},
      "762dc5fb47754c9a9db0bdf659286709":{
        "scriptId":"u26"},
      "680b7a13f6b944feb7e82998563637f9":{
        "scriptId":"u27"},
      "4d7292103726456a963a15507a1e2755":{
        "scriptId":"u28"},
      "8b05e2b571f441e6881f0dfdb45e1763":{
        "scriptId":"u29"}},
    "3b88108d1fa846ddb2b8244a66ef8ddf":{
      "scriptId":"u30"},
    "8e4cf0a8ae0e43d683f8864804e8d57a":{
      "scriptId":"u31"},
    "7d85bbacbdae4abca31e8d1a8d808d9c":{
      "scriptId":"u32"},
    "36ab025bd3b2432c836ee7ccf03018e0":{
      "scriptId":"u33"},
    "76f84f261c96488080a626e520e5f946":{
      "scriptId":"u34"},
    "96b64a272252435aab5772a89e52387a":{
      "scriptId":"u35"},
    "eeba11f5bd744ed8adcdf9aee6a78335":{
      "scriptId":"u36"},
    "8ae968946ef24835a98a532e6fe8a8ec":{
      "scriptId":"u37"},
    "5c3391d7bbe943b0bf44f5f67f727682":{
      "scriptId":"u38"},
    "4ae97deab92843b8b152dfdc05985438":{
      "scriptId":"u39"},
    "5c6aece25b8d4a9f9c4d1c3340bcade0":{
      "scriptId":"u40"},
    "1df1038b19ff44fe83ccc1b6e41e0b94":{
      "scriptId":"u41"},
    "53dfb69856f54847b65729a7e8537a24":{
      "scriptId":"u42"},
    "cb4c67c2dc6e4fe08aa870c47acc6ee6":{
      "scriptId":"u43"},
    "999bf05491704b71878da72485644654":{
      "scriptId":"u44"},
    "718540553a61418f8566db593ed33a37":{
      "scriptId":"u45"},
    "7d286e9dc3b74f2b845ce0a59a476229":{
      "scriptId":"u46"},
    "8928c81715324c2487509ec139ae7c56":{
      "scriptId":"u47"},
    "94e5c3c3996f4dab9651ef0716b6a2eb":{
      "scriptId":"u48"},
    "5582f3e489af45bdb546cacefa78ce85":{
      "scriptId":"u49"},
    "55107131750d42ca890faa994566424d":{
      "scriptId":"u50"},
    "08cd74d4ab6e49918276ac73e4c2cc58":{
      "scriptId":"u51"},
    "f569d770eb0248cfa4fe66f8efb7b95f":{
      "scriptId":"u52"},
    "d75649696a084ebab97fdb5ca4ae93ed":{
      "scriptId":"u53"},
    "b4bd30f169a14a219da3ee7b30036d8f":{
      "scriptId":"u54"},
    "33705a1715b34752a6c0a9d8e4506675":{
      "scriptId":"u55"},
    "be8dccf1340d44a4a7df8bd7ed9d1409":{
      "scriptId":"u56"},
    "3e36d471f6d3499b8fbb8ded67af13c7":{
      "scriptId":"u57"},
    "76eeea9294e84a64a7f1f259d860772a":{
      "scriptId":"u58"},
    "e73192537d5b4c16b54df87dc88c50be":{
      "scriptId":"u59"},
    "06559bd826594d56880ffc4b9bc71e2d":{
      "scriptId":"u60"},
    "ac68cef514814bbdaa4bec159a3ce847":{
      "scriptId":"u61"},
    "fd854e93ed424bdba49a72da838143a6":{
      "scriptId":"u62"},
    "4099a0d18859411eb6a2e1ddfa8e5a35":{
      "scriptId":"u63"},
    "83cb33dc5ca34d61a85024ee962a2610":{
      "scriptId":"u64"},
    "53a4a6942a0c41c3a1df0e2f028ff775":{
      "scriptId":"u65"},
    "3587aa3f3f1141a78e9e1ab8f750d7b4":{
      "scriptId":"u66"},
    "6fc49f4a64e0438b9bb71e287d1a4008":{
      "scriptId":"u67"},
    "a2e6ef6730ee4930b9afabd55f5ea995":{
      "scriptId":"u68"},
    "a6e2186327fe47bfb12b8a9ba34a5f52":{
      "scriptId":"u69"},
    "35037caee6984c6888cce89eb209bf8b":{
      "scriptId":"u70"},
    "6995cf700760463f94805d59406db313":{
      "scriptId":"u71"},
    "3145653e5843417a81a5c9d860106801":{
      "scriptId":"u72"},
    "2a081202137442b78423b821524774eb":{
      "scriptId":"u73"},
    "9f3206de8f3a4d38878f7e566ac6fa80":{
      "scriptId":"u74"},
    "a3512fbcbeea45fe823387dd48295e95":{
      "scriptId":"u75"},
    "0249e0c7bf0a4073ab48376659a8e66c":{
      "scriptId":"u76"},
    "2d3ec490225a45868091aa54d64af497":{
      "scriptId":"u77"},
    "c6a31298947a49949dcc322f47c8fedd":{
      "scriptId":"u78"}}});