$axure.loadCurrentPage({
  "url":"调度中心首页.html",
  "generationDate":new Date(1401345412674.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c608ba86d2ce4da68179d8a567a41358",
    "type":"Axure:Page",
    "name":"调度中心首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"62742dd28c9142789c44267a54a4cff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":1260,
              "height":1080}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"149a77555bd943e594c13cbecefe4b07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":1260,
                  "height":1080}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/调度中心首页/u0.png"}},
{
          "id":"81331ad6eddd415eb4dad4dc6d66304a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":99},
            "size":{
              "width":607,
              "height":632}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85392100f24d44ef87b1dd7273bc28b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":99},
                "size":{
                  "width":607,
                  "height":632}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u2.jpg"}},
{
          "id":"4aeb593af4cc44308ca0534102361467",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":78,
              "height":1080},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a3d27cf16df45be8ba19d7441a9d43e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":78,
                  "height":1080},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/调度中心首页/u4.png"}},
{
          "id":"fb341a06fe87425e99a3cc350c225568",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'ArialMT', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":104,
              "y":22},
            "size":{
              "width":149,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27c61ffa64684398ace2a80c3994ea19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'ArialMT', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":104,
                  "y":22},
                "size":{
                  "width":149,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d308328d11b412ba14c41f399a478a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'ArialMT', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":589,
              "y":26},
            "size":{
              "width":231,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28764c63db9a494db7d744276e2f59f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'ArialMT', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":589,
                  "y":26},
                "size":{
                  "width":231,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ee42cefb2594336984189f42ee73cb2",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":299,
              "y":27},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1f3e2ffdda545c5a56815cdf8b25880",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":299,
                  "y":27},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"5ee5f4f818954cfd9b4455356d48aa07",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":369,
              "y":27},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f73014c092a4a0681120217b7b5d0f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":369,
                  "y":27},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"734a85f6ab2d41a187d7cb650c4b971d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF0AA39,
                  "opacity":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0AA39}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}}},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFF3F7FA},
{
                  "color":0xFFF3F7FA},
{
                  "color":0xFFDFE8ED},
{
                  "color":0xFFDFE8ED}]},
            "location":{
              "x":434,
              "y":22},
            "size":{
              "width":63,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF9CCBF7},
            "cornerRadiusTopLeft":"4.333344"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e9449ce6b7c4464914f9f1c286825d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF0AA39,
                      "opacity":1},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF0AA39}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}}},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFF3F7FA},
{
                      "color":0xFFF3F7FA},
{
                      "color":0xFFDFE8ED},
{
                      "color":0xFFDFE8ED}]},
                "location":{
                  "x":434,
                  "y":22},
                "size":{
                  "width":63,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF9CCBF7},
                "cornerRadiusTopLeft":"4.333344"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u14.png",
            "selected~":"images/新调度中心/u14_selected.png",
            "mouseOver~":"images/新调度中心/u14_mouseOver.png"}},
{
          "id":"a236e9f4ff7948b68334896ce77b7a6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF2E3E4E},
            "location":{
              "x":86,
              "y":54},
            "size":{
              "width":1169,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f035a5c92454495bb8d387169bea014a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2E3E4E},
                "location":{
                  "x":86,
                  "y":54},
                "size":{
                  "width":1169,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u16.png"}},
{
          "id":"faf3adf2f79f4358a2166033d37b39c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":29},
            "size":{
              "width":43,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65fbd00eaa63403fa0f7abd677d9daa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":29},
                "size":{
                  "width":43,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新调度中心/u173.png"}},
{
          "id":"a25a349dd97b4ccda216fe2108747462",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":148,
              "y":62},
            "size":{
              "width":47,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"634a3c2ad0e74528a74bbde8b2d63ed7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":148,
                  "y":62},
                "size":{
                  "width":47,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"703e63201f7c48019e38fa3917d69ec9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":60},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d204d8c8ba7745ef9c3cf14a607fbed6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":103,
                  "y":60},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u228.png"}},
{
          "id":"2ec3dc96542c4259ac3cac4a91e3e283",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":62},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5ef1a62b91845749e4b821fea5c0dcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":62},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u230.png"}},
{
          "id":"bec6a2481c0d497b9d5732f0f7b046d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":89,
              "y":100},
            "size":{
              "width":551,
              "height":630},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca20233ad3444a5898ed1d5b25c74f4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":89,
                  "y":100},
                "size":{
                  "width":551,
                  "height":630},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/调度中心首页/u26.png"}},
{
          "id":"6d9390287dad4c2dbc1030e17c9b1c51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":90,
              "y":734},
            "size":{
              "width":1165,
              "height":346},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b74ef8b5719547d290e76c3ebba2901a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":90,
                  "y":734},
                "size":{
                  "width":1165,
                  "height":346},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/调度中心首页/u28.png"}},
{
          "id":"f796444063e84c8fb1d86d5fb25b2870",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":650,
              "y":99},
            "size":{
              "width":607,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f24994454d414d00acac03950a87bf49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":650,
                  "y":99},
                "size":{
                  "width":607,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/调度中心首页/u30.png"}},
{
          "id":"7699076da636425bbcbaba175e01fcc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":1064,
              "y":22},
            "size":{
              "width":191,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"164af4191b5d47e0b6f6654c2cb422b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":1064,
                  "y":22},
                "size":{
                  "width":191,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u246.png"}},
{
          "id":"5960814e795b464bb791c559851f9a7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":974,
              "y":31},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8df9644a8745464f8d462492f89ace5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":974,
                  "y":31},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aca9598af6f34ca6888b2268a0a8a13e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1229,
              "y":22},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85aebe1f24234c239841786e85fcb83e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1229,
                  "y":22},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u250.png"}},
{
          "id":"bd8e8686df2e4868a963c0ef89db5c33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":742,
              "y":102},
            "size":{
              "width":375,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a650f2de7614972b1397ecbb8c7ae05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":742,
                  "y":102},
                "size":{
                  "width":375,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u234.png"}},
{
          "id":"cde3cb37ca1e432383b5680ecb658432",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1086,
              "y":109},
            "size":{
              "width":26,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d0b89038ec2438497815cfed55b429f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1086,
                  "y":109},
                "size":{
                  "width":26,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u236.png"}},
{
          "id":"1171c5f0a20a4cd18d8c3ddc96c3ce73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1186,
              "y":103},
            "size":{
              "width":67,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cc16fc871734ffa8279a09e574c9add",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1186,
                  "y":103},
                "size":{
                  "width":67,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u238.png"}},
{
          "id":"4d13b5f034904af791a1aabe65f7d513",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1119,
              "y":103},
            "size":{
              "width":67,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8da2eed6c40140be891671408041cd53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1119,
                  "y":103},
                "size":{
                  "width":67,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u238.png"}},
{
          "id":"6a45eb599bf24de2a1f8febc04746c2b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":120},
            "size":{
              "width":38,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ea693ec21784846940f5fbb335937c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":120},
                "size":{
                  "width":38,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u383.png"}},
{
          "id":"9d9dd7ef3f9841249f12c2c6875aac18",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":220},
            "size":{
              "width":38,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25c469886a0f41bfb02aab60a90a1557",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":220},
                "size":{
                  "width":38,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u385.png"}},
{
          "id":"95a1184b419c45b581635bc06d0cecae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":324},
            "size":{
              "width":38,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38f10408da0640f489555d63730550c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":324},
                "size":{
                  "width":38,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u387.png"}},
{
          "id":"8d43e39bb9ab4b49b65c334dda6d1a53",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":19,
              "y":158},
            "size":{
              "width":53,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9a9c7aecbf1483694af5a1ba58d177a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":158},
                "size":{
                  "width":53,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1178c7298394cb8ac88efc0d483f8b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":20,
              "y":261},
            "size":{
              "width":53,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b1ad48361924084a11c5bc7dd8b02d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":261},
                "size":{
                  "width":53,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1884cd070a3f4bd1bb12c225ac8d6a6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei-Bold', 'Microsoft YaHei Bold', 'Microsoft YaHei'",
            "fontSize":"13px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":26,
              "y":362},
            "size":{
              "width":40,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acc01c708e4342afb6da13257ca0c2b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei-Bold', 'Microsoft YaHei Bold', 'Microsoft YaHei'",
                "fontSize":"13px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":26,
                  "y":362},
                "size":{
                  "width":40,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc130fd67cc44d2899ea0d62281adf35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":417},
            "size":{
              "width":38,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de710c0400b04c048d2eec975c59ab03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":417},
                "size":{
                  "width":38,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u395.png"}},
{
          "id":"8336ac4d4843426f94182c4bfa402862",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei-Bold', 'Microsoft YaHei Bold', 'Microsoft YaHei'",
            "fontSize":"13px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":27,
              "y":453},
            "size":{
              "width":40,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63856f68fb2f477eb578355f4c319c76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei-Bold', 'Microsoft YaHei Bold', 'Microsoft YaHei'",
                "fontSize":"13px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":453},
                "size":{
                  "width":40,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de491ef9771347a7b03717ed6d43446d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":610},
            "size":{
              "width":38,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b9fae60f73b40ed82800673c5b8bda6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":610},
                "size":{
                  "width":38,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u399.png"}},
{
          "id":"a89433de07f14d87a78593e45bce2048",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":22,
              "y":648},
            "size":{
              "width":53,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e740e51c71da4782bffe7d15127cfc5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":648},
                "size":{
                  "width":53,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1ff1dd94a0d4582a5ea8a6b34b60fed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":707},
            "size":{
              "width":38,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54940d4171db4a58b7a95f9011406139",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":707},
                "size":{
                  "width":38,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u403.png"}},
{
          "id":"284f5716224b4dce9c1071b4713fadb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":22,
              "y":745},
            "size":{
              "width":53,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33fc780080ea4ed9a8365d957073f713",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":745},
                "size":{
                  "width":53,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b31b9c836b824e5e88b02a9063043f3e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":317},
            "size":{
              "width":13,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ee5ffadda814b60b90b10f8af116e77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":317},
                "size":{
                  "width":13,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u407.png"}},
{
          "id":"d7febb7549f1420fbf82376b014c6e63",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":507},
            "size":{
              "width":38,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2946147306104b0a9ab3cfbee6a196df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":507},
                "size":{
                  "width":38,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新调度中心/u409.png"}},
{
          "id":"0b16370bcaed48f58ee17153f4936c1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei-Bold', 'Microsoft YaHei Bold', 'Microsoft YaHei'",
            "fontSize":"13px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":27,
              "y":543},
            "size":{
              "width":40,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2b1c67831714b11b66b577d1134efb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei-Bold', 'Microsoft YaHei Bold', 'Microsoft YaHei'",
                "fontSize":"13px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":543},
                "size":{
                  "width":40,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "62742dd28c9142789c44267a54a4cff7":{
      "scriptId":"u0"},
    "149a77555bd943e594c13cbecefe4b07":{
      "scriptId":"u1"},
    "81331ad6eddd415eb4dad4dc6d66304a":{
      "scriptId":"u2"},
    "85392100f24d44ef87b1dd7273bc28b1":{
      "scriptId":"u3"},
    "4aeb593af4cc44308ca0534102361467":{
      "scriptId":"u4"},
    "2a3d27cf16df45be8ba19d7441a9d43e":{
      "scriptId":"u5"},
    "fb341a06fe87425e99a3cc350c225568":{
      "scriptId":"u6"},
    "27c61ffa64684398ace2a80c3994ea19":{
      "scriptId":"u7"},
    "0d308328d11b412ba14c41f399a478a4":{
      "scriptId":"u8"},
    "28764c63db9a494db7d744276e2f59f4":{
      "scriptId":"u9"},
    "1ee42cefb2594336984189f42ee73cb2":{
      "scriptId":"u10"},
    "c1f3e2ffdda545c5a56815cdf8b25880":{
      "scriptId":"u11"},
    "5ee5f4f818954cfd9b4455356d48aa07":{
      "scriptId":"u12"},
    "6f73014c092a4a0681120217b7b5d0f9":{
      "scriptId":"u13"},
    "734a85f6ab2d41a187d7cb650c4b971d":{
      "scriptId":"u14"},
    "0e9449ce6b7c4464914f9f1c286825d8":{
      "scriptId":"u15"},
    "a236e9f4ff7948b68334896ce77b7a6b":{
      "scriptId":"u16"},
    "f035a5c92454495bb8d387169bea014a":{
      "scriptId":"u17"},
    "faf3adf2f79f4358a2166033d37b39c1":{
      "scriptId":"u18"},
    "65fbd00eaa63403fa0f7abd677d9daa7":{
      "scriptId":"u19"},
    "a25a349dd97b4ccda216fe2108747462":{
      "scriptId":"u20"},
    "634a3c2ad0e74528a74bbde8b2d63ed7":{
      "scriptId":"u21"},
    "703e63201f7c48019e38fa3917d69ec9":{
      "scriptId":"u22"},
    "d204d8c8ba7745ef9c3cf14a607fbed6":{
      "scriptId":"u23"},
    "2ec3dc96542c4259ac3cac4a91e3e283":{
      "scriptId":"u24"},
    "a5ef1a62b91845749e4b821fea5c0dcc":{
      "scriptId":"u25"},
    "bec6a2481c0d497b9d5732f0f7b046d5":{
      "scriptId":"u26"},
    "ca20233ad3444a5898ed1d5b25c74f4d":{
      "scriptId":"u27"},
    "6d9390287dad4c2dbc1030e17c9b1c51":{
      "scriptId":"u28"},
    "b74ef8b5719547d290e76c3ebba2901a":{
      "scriptId":"u29"},
    "f796444063e84c8fb1d86d5fb25b2870":{
      "scriptId":"u30"},
    "f24994454d414d00acac03950a87bf49":{
      "scriptId":"u31"},
    "7699076da636425bbcbaba175e01fcc9":{
      "scriptId":"u32"},
    "164af4191b5d47e0b6f6654c2cb422b1":{
      "scriptId":"u33"},
    "5960814e795b464bb791c559851f9a7f":{
      "scriptId":"u34"},
    "8df9644a8745464f8d462492f89ace5f":{
      "scriptId":"u35"},
    "aca9598af6f34ca6888b2268a0a8a13e":{
      "scriptId":"u36"},
    "85aebe1f24234c239841786e85fcb83e":{
      "scriptId":"u37"},
    "bd8e8686df2e4868a963c0ef89db5c33":{
      "scriptId":"u38"},
    "5a650f2de7614972b1397ecbb8c7ae05":{
      "scriptId":"u39"},
    "cde3cb37ca1e432383b5680ecb658432":{
      "scriptId":"u40"},
    "5d0b89038ec2438497815cfed55b429f":{
      "scriptId":"u41"},
    "1171c5f0a20a4cd18d8c3ddc96c3ce73":{
      "scriptId":"u42"},
    "6cc16fc871734ffa8279a09e574c9add":{
      "scriptId":"u43"},
    "4d13b5f034904af791a1aabe65f7d513":{
      "scriptId":"u44"},
    "8da2eed6c40140be891671408041cd53":{
      "scriptId":"u45"},
    "6a45eb599bf24de2a1f8febc04746c2b":{
      "scriptId":"u46"},
    "0ea693ec21784846940f5fbb335937c4":{
      "scriptId":"u47"},
    "9d9dd7ef3f9841249f12c2c6875aac18":{
      "scriptId":"u48"},
    "25c469886a0f41bfb02aab60a90a1557":{
      "scriptId":"u49"},
    "95a1184b419c45b581635bc06d0cecae":{
      "scriptId":"u50"},
    "38f10408da0640f489555d63730550c3":{
      "scriptId":"u51"},
    "8d43e39bb9ab4b49b65c334dda6d1a53":{
      "scriptId":"u52"},
    "c9a9c7aecbf1483694af5a1ba58d177a":{
      "scriptId":"u53"},
    "f1178c7298394cb8ac88efc0d483f8b5":{
      "scriptId":"u54"},
    "8b1ad48361924084a11c5bc7dd8b02d0":{
      "scriptId":"u55"},
    "1884cd070a3f4bd1bb12c225ac8d6a6f":{
      "scriptId":"u56"},
    "acc01c708e4342afb6da13257ca0c2b1":{
      "scriptId":"u57"},
    "fc130fd67cc44d2899ea0d62281adf35":{
      "scriptId":"u58"},
    "de710c0400b04c048d2eec975c59ab03":{
      "scriptId":"u59"},
    "8336ac4d4843426f94182c4bfa402862":{
      "scriptId":"u60"},
    "63856f68fb2f477eb578355f4c319c76":{
      "scriptId":"u61"},
    "de491ef9771347a7b03717ed6d43446d":{
      "scriptId":"u62"},
    "0b9fae60f73b40ed82800673c5b8bda6":{
      "scriptId":"u63"},
    "a89433de07f14d87a78593e45bce2048":{
      "scriptId":"u64"},
    "e740e51c71da4782bffe7d15127cfc5e":{
      "scriptId":"u65"},
    "a1ff1dd94a0d4582a5ea8a6b34b60fed":{
      "scriptId":"u66"},
    "54940d4171db4a58b7a95f9011406139":{
      "scriptId":"u67"},
    "284f5716224b4dce9c1071b4713fadb4":{
      "scriptId":"u68"},
    "33fc780080ea4ed9a8365d957073f713":{
      "scriptId":"u69"},
    "b31b9c836b824e5e88b02a9063043f3e":{
      "scriptId":"u70"},
    "6ee5ffadda814b60b90b10f8af116e77":{
      "scriptId":"u71"},
    "d7febb7549f1420fbf82376b014c6e63":{
      "scriptId":"u72"},
    "2946147306104b0a9ab3cfbee6a196df":{
      "scriptId":"u73"},
    "0b16370bcaed48f58ee17153f4936c1f":{
      "scriptId":"u74"},
    "b2b1c67831714b11b66b577d1134efb6":{
      "scriptId":"u75"}}});