$axure.loadCurrentPage({
  "url":"修改成功_1.html",
  "generationDate":new Date(1401345419950.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c06af76e19b748edb29d344bb2b1ad08",
    "type":"Axure:Page",
    "name":"修改成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a5e786e85e74445b855d404e32f16ffc",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"d1816b87768546869fbf5f5fc4d1ba7d"},
{
          "id":"fe9d913a585f475a848d4db57727dff1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":349,
              "y":144},
            "size":{
              "width":181,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70ab3959be0b44159910f248c2a75342",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":349,
                  "y":144},
                "size":{
                  "width":181,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20b44154d05543c4897cea8422c8bddb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":130},
            "size":{
              "width":64,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2d74c1960e847f4857decc36eee8ca6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":130},
                "size":{
                  "width":64,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增成功/u32.png"}},
{
          "id":"8be31ffd8be343199bb47a39e3b7db3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":349,
              "y":245},
            "size":{
              "width":181,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2097feae3d07450299d85ac0e519c6a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":349,
                  "y":245},
                "size":{
                  "width":181,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e79ab3218664d769f0e1d3fa1ca904d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009966},
            "location":{
              "x":10,
              "y":658},
            "size":{
              "width":12,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e12619ef2943435880ddab5bf66a36ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009966},
                "location":{
                  "x":10,
                  "y":658},
                "size":{
                  "width":12,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/常用信息/u34.png"}}]}},
  "masters":{
    "d1816b87768546869fbf5f5fc4d1ba7d":{
      "packageId":"d1816b87768546869fbf5f5fc4d1ba7d",
      "type":"Axure:Master",
      "name":"公共功能",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a95411bbce364a6e8352ec8cb4ef3e3a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":38,
                "y":20},
              "size":{
                "width":1280,
                "height":1210},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF777777}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2c263b778f3a4f8db528af20a297dcb2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":38,
                    "y":20},
                  "size":{
                    "width":1280,
                    "height":1210},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF777777}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u1.png"}},
{
            "id":"fda5b479da1c4a31aa6e7e1484e98d5a",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":207,
                "y":21},
              "size":{
                "width":10,
                "height":1209},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF777777}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/u3_line.png"}},
{
            "id":"e15a802047e24c6a8c6bbdd84bd40c4d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":93},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7186e364edd54114b5476b016aa6847d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":93},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 常用信息",
                        "target":{
                          "targetType":"page",
                          "url":"常用信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"f45315029c354fc2bb32d5df72b94467",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":159},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9427c2c800c545ddb79693d3c6922018",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":159},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 内部公告",
                        "target":{
                          "targetType":"page",
                          "url":"内部公告.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"1c9d8c816b3d403ebd4083fee7459de0",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":233},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"436c05d31fb240c7a15355b46989eb53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":233},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 公告管理",
                        "target":{
                          "targetType":"page",
                          "url":"公告管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"3755540f080e46beb2bd3815ca11ae37",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":397},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7ffa024de06848fc937f793c3f8211b0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":397},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 新调度中心",
                        "target":{
                          "targetType":"page",
                          "url":"新调度中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"d3eb8bdcb593413584c06e8384bee766",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":462},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a0d859f938e64a78871be545d525b983",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":462},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 短信平台",
                        "target":{
                          "targetType":"page",
                          "url":"短信平台.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"06ba4fbbbbfb4f1fb3caaaea015f6da1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":535},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"52dc334939f3434eb5a5560cdc121ba7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":535},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 作废订单",
                        "target":{
                          "targetType":"page",
                          "url":"作废订单.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"2e73a5717ec84c19b9077d7d2721132d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":608},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7a610aef328f4144b80d2dd241739021",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":608},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 通话记录",
                        "target":{
                          "targetType":"page",
                          "url":"通话记录.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"2218fe453a384502a76a6eb94c7ebbf1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":680},
              "size":{
                "width":121,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fb59f2b7a37d4392a956f2da24ef6502",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":680},
                  "size":{
                    "width":121,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 记录问题管理",
                        "target":{
                          "targetType":"page",
                          "url":"记录问题管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"c114e5842caf40d59a85dc40d53ff196",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":752},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1e1fc06d542745b4acd841910e45f4ad",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":752},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 修改密码",
                        "target":{
                          "targetType":"page",
                          "url":"修改密码.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"d0ad9c0b5ac3427d8a864e7a4955d76e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":74,
                "y":264},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7052978533a42b79d6f7beda7a8d046",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":74,
                    "y":264},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 新增公告",
                        "target":{
                          "targetType":"page",
                          "url":"新增公告.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"740cec6f294146f69cc993d8006577b3",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":74,
                "y":291},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f8f6f0e9b3f5432391c39effc5eb5b09",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":74,
                    "y":291},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 公司公告",
                        "target":{
                          "targetType":"page",
                          "url":"公司公告.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"762dc5fb47754c9a9db0bdf659286709",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":74,
                "y":318},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"680b7a13f6b944feb7e82998563637f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":74,
                    "y":318},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 内部公告",
                        "target":{
                          "targetType":"page",
                          "url":"内部公告_1.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"4d7292103726456a963a15507a1e2755",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":74,
                "y":345},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8b05e2b571f441e6881f0dfdb45e1763",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":74,
                    "y":345},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 培训教程",
                        "target":{
                          "targetType":"page",
                          "url":"培训教程.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "a5e786e85e74445b855d404e32f16ffc":{
      "scriptId":"u0",
      "a95411bbce364a6e8352ec8cb4ef3e3a":{
        "scriptId":"u1"},
      "2c263b778f3a4f8db528af20a297dcb2":{
        "scriptId":"u2"},
      "fda5b479da1c4a31aa6e7e1484e98d5a":{
        "scriptId":"u3"},
      "e15a802047e24c6a8c6bbdd84bd40c4d":{
        "scriptId":"u4"},
      "7186e364edd54114b5476b016aa6847d":{
        "scriptId":"u5"},
      "f45315029c354fc2bb32d5df72b94467":{
        "scriptId":"u6"},
      "9427c2c800c545ddb79693d3c6922018":{
        "scriptId":"u7"},
      "1c9d8c816b3d403ebd4083fee7459de0":{
        "scriptId":"u8"},
      "436c05d31fb240c7a15355b46989eb53":{
        "scriptId":"u9"},
      "3755540f080e46beb2bd3815ca11ae37":{
        "scriptId":"u10"},
      "7ffa024de06848fc937f793c3f8211b0":{
        "scriptId":"u11"},
      "d3eb8bdcb593413584c06e8384bee766":{
        "scriptId":"u12"},
      "a0d859f938e64a78871be545d525b983":{
        "scriptId":"u13"},
      "06ba4fbbbbfb4f1fb3caaaea015f6da1":{
        "scriptId":"u14"},
      "52dc334939f3434eb5a5560cdc121ba7":{
        "scriptId":"u15"},
      "2e73a5717ec84c19b9077d7d2721132d":{
        "scriptId":"u16"},
      "7a610aef328f4144b80d2dd241739021":{
        "scriptId":"u17"},
      "2218fe453a384502a76a6eb94c7ebbf1":{
        "scriptId":"u18"},
      "fb59f2b7a37d4392a956f2da24ef6502":{
        "scriptId":"u19"},
      "c114e5842caf40d59a85dc40d53ff196":{
        "scriptId":"u20"},
      "1e1fc06d542745b4acd841910e45f4ad":{
        "scriptId":"u21"},
      "d0ad9c0b5ac3427d8a864e7a4955d76e":{
        "scriptId":"u22"},
      "c7052978533a42b79d6f7beda7a8d046":{
        "scriptId":"u23"},
      "740cec6f294146f69cc993d8006577b3":{
        "scriptId":"u24"},
      "f8f6f0e9b3f5432391c39effc5eb5b09":{
        "scriptId":"u25"},
      "762dc5fb47754c9a9db0bdf659286709":{
        "scriptId":"u26"},
      "680b7a13f6b944feb7e82998563637f9":{
        "scriptId":"u27"},
      "4d7292103726456a963a15507a1e2755":{
        "scriptId":"u28"},
      "8b05e2b571f441e6881f0dfdb45e1763":{
        "scriptId":"u29"}},
    "fe9d913a585f475a848d4db57727dff1":{
      "scriptId":"u30"},
    "70ab3959be0b44159910f248c2a75342":{
      "scriptId":"u31"},
    "20b44154d05543c4897cea8422c8bddb":{
      "scriptId":"u32"},
    "c2d74c1960e847f4857decc36eee8ca6":{
      "scriptId":"u33"},
    "8be31ffd8be343199bb47a39e3b7db3f":{
      "scriptId":"u34"},
    "2097feae3d07450299d85ac0e519c6a0":{
      "scriptId":"u35"},
    "0e79ab3218664d769f0e1d3fa1ca904d":{
      "scriptId":"u36"},
    "e12619ef2943435880ddab5bf66a36ed":{
      "scriptId":"u37"}}});