$axure.loadCurrentPage({
  "url":"新增问题.html",
  "generationDate":new Date(1401345418294.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1d2839ff748f4cd28924059c1c2afb49",
    "type":"Axure:Page",
    "name":"新增问题",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"75e443454864409ebb58c69bbbdd0163",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"d1816b87768546869fbf5f5fc4d1ba7d"},
{
          "id":"4bf7ce37014b43869f610ca851d66a1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009966},
            "location":{
              "x":10,
              "y":660},
            "size":{
              "width":12,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"622761fdffe348b59db054b57db34a31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009966},
                "location":{
                  "x":10,
                  "y":660},
                "size":{
                  "width":12,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/常用信息/u34.png"}},
{
          "id":"cb9315282cb941c2bd14ed80a8d18a40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":50},
            "size":{
              "width":1040,
              "height":710},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3ab0959286e42b4acac3ddb0a2e2e59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":50},
                "size":{
                  "width":1040,
                  "height":710},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增问题/u32.png"}},
{
          "id":"29ca99e339894d749c485f35b324d4df",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":84},
            "size":{
              "width":1040,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/记录问题管理/u34_line.png"}},
{
          "id":"19a9c19e9e274f839b12267bc693df0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei-Bold', 'Microsoft YaHei Bold', 'Microsoft YaHei'",
            "fontSize":"16px",
            "location":{
              "x":226,
              "y":61},
            "size":{
              "width":65,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2254b7c9b89c4cefa36258f8a9db2f8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei-Bold', 'Microsoft YaHei Bold', 'Microsoft YaHei'",
                "fontSize":"16px",
                "location":{
                  "x":226,
                  "y":61},
                "size":{
                  "width":65,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2abbd199cc64c8d8f084d50701611fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":249,
              "y":113},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcaa944aadb8411e853e195d48cf5d84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":249,
                  "y":113},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd6b653e39b24ea8a08cda03980ca617",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":141},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"f6458c0de21d4d23978b56fcff6173af",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":422,
              "y":112},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b80e25d4ec8d49c19175ceba4498c8d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":422,
                  "y":112},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd18cdc734b2490cb8311589522f25e1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":422,
              "y":140},
            "size":{
              "width":108,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"a1e6059cbfa249f88633eb9a6eec6632",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":610,
              "y":112},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50ecc7254f424c2a84c206d74bfa6c11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":610,
                  "y":112},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edecf371569c45df8802b44beabb63a9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":140},
            "size":{
              "width":160,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"483d745183f54b21885fb50ebc4ad72e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":849,
              "y":112},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"953ba997e4a5413e94c136ac3e36b5ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":849,
                  "y":112},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bf7ea0bebe146728c72fd4b7d225479",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":849,
              "y":140},
            "size":{
              "width":131,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"338aab3411724d6e8024db40623aadfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":1060,
              "y":112},
            "size":{
              "width":97,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87669eecef804567bf0e737ded8938d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":1060,
                  "y":112},
                "size":{
                  "width":97,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96cc048647384ae28ddf41730b24aa0e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":1060,
              "y":140},
            "size":{
              "width":160,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"ac6ffee24cc5438ea0450ded97ddd834",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":249,
              "y":220},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c91d7a644bd74c78bc5ec17120463b84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":249,
                  "y":220},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23b5a28e68e14066bcc036b340c79ff3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":422,
              "y":220},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47563f0f8fb74e1898c007389c174110",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":422,
                  "y":220},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a02504330c8b49e9a0c279e37a406dac",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":249,
              "y":251},
            "size":{
              "width":120,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"a6cdb3b2ec5c4763a28c42e7e7fcfc83",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":422,
              "y":251},
            "size":{
              "width":81,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"b16913599e1e498ea36b2922a8c7149c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":506,
              "y":251},
            "size":{
              "width":80,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"394e6ad871b94651b79031bbf252c1fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":620,
              "y":220},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92f79e70071a405ba224173466972560",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":620,
                  "y":220},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b882c277e79a418bb1917b26282e244a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":620,
              "y":251},
            "size":{
              "width":81,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"e141f257ea2a40b29a6d1add6438b45f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":249,
              "y":312},
            "size":{
              "width":81,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ff4bb832bbc47f7a2e9a844017b7e10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":249,
                  "y":312},
                "size":{
                  "width":81,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d07c43460fdc4aa0895ba20b984bf219",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":351},
            "size":{
              "width":851,
              "height":119}},
          "adaptiveStyles":{
}},
{
          "id":"f17d83afe53f448ca9498412d35b7145",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":249,
              "y":501},
            "size":{
              "width":118,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe6b1ff6897447819198aa9460e01d7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":249,
                  "y":501},
                "size":{
                  "width":118,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22fe9777da254d1db3d4836a04c881e8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":529},
            "size":{
              "width":851,
              "height":119}},
          "adaptiveStyles":{
}},
{
          "id":"05ed305645314a16af36399a79d3fff3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":249,
              "y":690},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cc6635189ce42f09f523ad2d97f838b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":249,
                  "y":690},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 记录问题管理",
                      "target":{
                        "targetType":"page",
                        "url":"记录问题管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/查看公告/u47.png"}},
{
          "id":"0af5395b7ceb40f086ba286b2626ceeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":491,
              "y":690},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ff68848f5124bf5a25f268b3cdcd49a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":491,
                  "y":690},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 记录问题管理",
                      "target":{
                        "targetType":"page",
                        "url":"记录问题管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/查看公告/u47.png"}}]}},
  "masters":{
    "d1816b87768546869fbf5f5fc4d1ba7d":{
      "packageId":"d1816b87768546869fbf5f5fc4d1ba7d",
      "type":"Axure:Master",
      "name":"公共功能",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a95411bbce364a6e8352ec8cb4ef3e3a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":38,
                "y":20},
              "size":{
                "width":1280,
                "height":1210},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF777777}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2c263b778f3a4f8db528af20a297dcb2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":38,
                    "y":20},
                  "size":{
                    "width":1280,
                    "height":1210},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF777777}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u1.png"}},
{
            "id":"fda5b479da1c4a31aa6e7e1484e98d5a",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":207,
                "y":21},
              "size":{
                "width":10,
                "height":1209},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF777777}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/u3_line.png"}},
{
            "id":"e15a802047e24c6a8c6bbdd84bd40c4d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":93},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7186e364edd54114b5476b016aa6847d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":93},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 常用信息",
                        "target":{
                          "targetType":"page",
                          "url":"常用信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"f45315029c354fc2bb32d5df72b94467",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":159},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9427c2c800c545ddb79693d3c6922018",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":159},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 内部公告",
                        "target":{
                          "targetType":"page",
                          "url":"内部公告.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"1c9d8c816b3d403ebd4083fee7459de0",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":233},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"436c05d31fb240c7a15355b46989eb53",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":233},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 公告管理",
                        "target":{
                          "targetType":"page",
                          "url":"公告管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"3755540f080e46beb2bd3815ca11ae37",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":397},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7ffa024de06848fc937f793c3f8211b0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":397},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 新调度中心",
                        "target":{
                          "targetType":"page",
                          "url":"新调度中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"d3eb8bdcb593413584c06e8384bee766",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":462},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a0d859f938e64a78871be545d525b983",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":462},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 短信平台",
                        "target":{
                          "targetType":"page",
                          "url":"短信平台.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"06ba4fbbbbfb4f1fb3caaaea015f6da1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":535},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"52dc334939f3434eb5a5560cdc121ba7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":535},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 作废订单",
                        "target":{
                          "targetType":"page",
                          "url":"作废订单.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"2e73a5717ec84c19b9077d7d2721132d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":608},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7a610aef328f4144b80d2dd241739021",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":608},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 通话记录",
                        "target":{
                          "targetType":"page",
                          "url":"通话记录.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"2218fe453a384502a76a6eb94c7ebbf1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":680},
              "size":{
                "width":121,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fb59f2b7a37d4392a956f2da24ef6502",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":680},
                  "size":{
                    "width":121,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 记录问题管理",
                        "target":{
                          "targetType":"page",
                          "url":"记录问题管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"c114e5842caf40d59a85dc40d53ff196",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'ArialMT', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":65,
                "y":752},
              "size":{
                "width":81,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1e1fc06d542745b4acd841910e45f4ad",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'ArialMT', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":65,
                    "y":752},
                  "size":{
                    "width":81,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 修改密码",
                        "target":{
                          "targetType":"page",
                          "url":"修改密码.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"d0ad9c0b5ac3427d8a864e7a4955d76e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":74,
                "y":264},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7052978533a42b79d6f7beda7a8d046",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":74,
                    "y":264},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 新增公告",
                        "target":{
                          "targetType":"page",
                          "url":"新增公告.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"740cec6f294146f69cc993d8006577b3",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":74,
                "y":291},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f8f6f0e9b3f5432391c39effc5eb5b09",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":74,
                    "y":291},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 公司公告",
                        "target":{
                          "targetType":"page",
                          "url":"公司公告.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"762dc5fb47754c9a9db0bdf659286709",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":74,
                "y":318},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"680b7a13f6b944feb7e82998563637f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":74,
                    "y":318},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 内部公告",
                        "target":{
                          "targetType":"page",
                          "url":"内部公告_1.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"4d7292103726456a963a15507a1e2755",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF006633,
                    "opacity":1}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0000CC,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}}},
              "location":{
                "x":74,
                "y":345},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8b05e2b571f441e6881f0dfdb45e1763",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'MicrosoftYaHei', 'Microsoft YaHei'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF006633,
                        "opacity":1}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000CC,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}}},
                  "location":{
                    "x":74,
                    "y":345},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 培训教程",
                        "target":{
                          "targetType":"page",
                          "url":"培训教程.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "75e443454864409ebb58c69bbbdd0163":{
      "scriptId":"u0",
      "a95411bbce364a6e8352ec8cb4ef3e3a":{
        "scriptId":"u1"},
      "2c263b778f3a4f8db528af20a297dcb2":{
        "scriptId":"u2"},
      "fda5b479da1c4a31aa6e7e1484e98d5a":{
        "scriptId":"u3"},
      "e15a802047e24c6a8c6bbdd84bd40c4d":{
        "scriptId":"u4"},
      "7186e364edd54114b5476b016aa6847d":{
        "scriptId":"u5"},
      "f45315029c354fc2bb32d5df72b94467":{
        "scriptId":"u6"},
      "9427c2c800c545ddb79693d3c6922018":{
        "scriptId":"u7"},
      "1c9d8c816b3d403ebd4083fee7459de0":{
        "scriptId":"u8"},
      "436c05d31fb240c7a15355b46989eb53":{
        "scriptId":"u9"},
      "3755540f080e46beb2bd3815ca11ae37":{
        "scriptId":"u10"},
      "7ffa024de06848fc937f793c3f8211b0":{
        "scriptId":"u11"},
      "d3eb8bdcb593413584c06e8384bee766":{
        "scriptId":"u12"},
      "a0d859f938e64a78871be545d525b983":{
        "scriptId":"u13"},
      "06ba4fbbbbfb4f1fb3caaaea015f6da1":{
        "scriptId":"u14"},
      "52dc334939f3434eb5a5560cdc121ba7":{
        "scriptId":"u15"},
      "2e73a5717ec84c19b9077d7d2721132d":{
        "scriptId":"u16"},
      "7a610aef328f4144b80d2dd241739021":{
        "scriptId":"u17"},
      "2218fe453a384502a76a6eb94c7ebbf1":{
        "scriptId":"u18"},
      "fb59f2b7a37d4392a956f2da24ef6502":{
        "scriptId":"u19"},
      "c114e5842caf40d59a85dc40d53ff196":{
        "scriptId":"u20"},
      "1e1fc06d542745b4acd841910e45f4ad":{
        "scriptId":"u21"},
      "d0ad9c0b5ac3427d8a864e7a4955d76e":{
        "scriptId":"u22"},
      "c7052978533a42b79d6f7beda7a8d046":{
        "scriptId":"u23"},
      "740cec6f294146f69cc993d8006577b3":{
        "scriptId":"u24"},
      "f8f6f0e9b3f5432391c39effc5eb5b09":{
        "scriptId":"u25"},
      "762dc5fb47754c9a9db0bdf659286709":{
        "scriptId":"u26"},
      "680b7a13f6b944feb7e82998563637f9":{
        "scriptId":"u27"},
      "4d7292103726456a963a15507a1e2755":{
        "scriptId":"u28"},
      "8b05e2b571f441e6881f0dfdb45e1763":{
        "scriptId":"u29"}},
    "4bf7ce37014b43869f610ca851d66a1a":{
      "scriptId":"u30"},
    "622761fdffe348b59db054b57db34a31":{
      "scriptId":"u31"},
    "cb9315282cb941c2bd14ed80a8d18a40":{
      "scriptId":"u32"},
    "e3ab0959286e42b4acac3ddb0a2e2e59":{
      "scriptId":"u33"},
    "29ca99e339894d749c485f35b324d4df":{
      "scriptId":"u34"},
    "19a9c19e9e274f839b12267bc693df0e":{
      "scriptId":"u35"},
    "2254b7c9b89c4cefa36258f8a9db2f8c":{
      "scriptId":"u36"},
    "e2abbd199cc64c8d8f084d50701611fd":{
      "scriptId":"u37"},
    "bcaa944aadb8411e853e195d48cf5d84":{
      "scriptId":"u38"},
    "fd6b653e39b24ea8a08cda03980ca617":{
      "scriptId":"u39"},
    "f6458c0de21d4d23978b56fcff6173af":{
      "scriptId":"u40"},
    "b80e25d4ec8d49c19175ceba4498c8d2":{
      "scriptId":"u41"},
    "cd18cdc734b2490cb8311589522f25e1":{
      "scriptId":"u42"},
    "a1e6059cbfa249f88633eb9a6eec6632":{
      "scriptId":"u43"},
    "50ecc7254f424c2a84c206d74bfa6c11":{
      "scriptId":"u44"},
    "edecf371569c45df8802b44beabb63a9":{
      "scriptId":"u45"},
    "483d745183f54b21885fb50ebc4ad72e":{
      "scriptId":"u46"},
    "953ba997e4a5413e94c136ac3e36b5ab":{
      "scriptId":"u47"},
    "2bf7ea0bebe146728c72fd4b7d225479":{
      "scriptId":"u48"},
    "338aab3411724d6e8024db40623aadfb":{
      "scriptId":"u49"},
    "87669eecef804567bf0e737ded8938d7":{
      "scriptId":"u50"},
    "96cc048647384ae28ddf41730b24aa0e":{
      "scriptId":"u51"},
    "ac6ffee24cc5438ea0450ded97ddd834":{
      "scriptId":"u52"},
    "c91d7a644bd74c78bc5ec17120463b84":{
      "scriptId":"u53"},
    "23b5a28e68e14066bcc036b340c79ff3":{
      "scriptId":"u54"},
    "47563f0f8fb74e1898c007389c174110":{
      "scriptId":"u55"},
    "a02504330c8b49e9a0c279e37a406dac":{
      "scriptId":"u56"},
    "a6cdb3b2ec5c4763a28c42e7e7fcfc83":{
      "scriptId":"u57"},
    "b16913599e1e498ea36b2922a8c7149c":{
      "scriptId":"u58"},
    "394e6ad871b94651b79031bbf252c1fc":{
      "scriptId":"u59"},
    "92f79e70071a405ba224173466972560":{
      "scriptId":"u60"},
    "b882c277e79a418bb1917b26282e244a":{
      "scriptId":"u61"},
    "e141f257ea2a40b29a6d1add6438b45f":{
      "scriptId":"u62"},
    "2ff4bb832bbc47f7a2e9a844017b7e10":{
      "scriptId":"u63"},
    "d07c43460fdc4aa0895ba20b984bf219":{
      "scriptId":"u64"},
    "f17d83afe53f448ca9498412d35b7145":{
      "scriptId":"u65"},
    "fe6b1ff6897447819198aa9460e01d7f":{
      "scriptId":"u66"},
    "22fe9777da254d1db3d4836a04c881e8":{
      "scriptId":"u67"},
    "05ed305645314a16af36399a79d3fff3":{
      "scriptId":"u68"},
    "9cc6635189ce42f09f523ad2d97f838b":{
      "scriptId":"u69"},
    "0af5395b7ceb40f086ba286b2626ceeb":{
      "scriptId":"u70"},
    "5ff68848f5124bf5a25f268b3cdcd49a":{
      "scriptId":"u71"}}});